### ISSUE TITLE
La dernière version (7.4.2?) de qrcode ne fonctionne pas

### ISSUE THREAD

**Issue by fenneclabs** [Korben00/AuthyExtractor#2]
(Je suis sur MacOS)

lors de l'install pip utilise:
`qrcode-7.4.2-py3-none-any.whl`

Et j'ai une erreur:
`    img.save(buffer, format="PNG") `
`TypeError: PyPNGImage.save() got an unexpected keyword argument 'format'`

Si je change html_table.py et utilise _img.save(buffer)_ tout fonctionne.

Je pense que ça serait mieux d'avoir des versions dans _requirements.txt_

**Comment by fenneclabs** [comment]
Merci Korben pour ce soft très utile et ton site qui est très agréable a lire :)

**Comment by jordichava** [comment]
Bonjour @fenneclabs
Tu as la même erreur que moi, je l'ai résolue comme ça :

[https://github.com/Korben00/authy-export/issues/3](url)

;)

**Comment by Korben00** [comment]
fixed
