### ISSUE TITLE
TypeError: PyPNGImage.save() got an unexpected keyword argument 'format'

### ISSUE THREAD

**Issue by jordichava** [Korben00/AuthyExtractor#3]
Bonjour,

Avant terminer, le terminal me montre :

```
File "/Users/jacksparrow/authy-export/functions/html_table.py", line 54, in htmltable
    img.save(buffer, format="PNG")
TypeError: PyPNGImage.save() got an unexpected keyword argument 'format'
```

Dans le fichier html_table.py (functions), ligne 54  `img.save(buffer, format="PNG")` en modifiant comme ça `img.save(buffer)` l'erreur est disparu et l'application fonctionne nickel.

Merci @Korben00  pour cette super application ;)

**Comment by Korben00** [comment]
fixed
